-- ============================================================
-- Reference data: sites, devices, interfaces, configs
--
-- This data is static (no timestamps that go stale), so it lives in SQL
-- where participants can read it directly. Time-dependent data
-- (tickets, messages) is generated by the seeder relative to run time.
--
-- Every row here is referenced by data/scenarios.md - do not edit one
-- without updating the other.
-- ============================================================

INSERT INTO sites (site_code, name_th, name_en, region) VALUES
    ('BKK', 'กรุงเทพมหานคร', 'Bangkok',   'Central'),
    ('NBI', 'นนทบุรี',        'Nonthaburi','Central');

-- ---------- 10 devices: 4 at BKK, 6 at NBI ----------

INSERT INTO devices (device_id, site_code, role, vendor, model, os_version, mgmt_ip, installed_on) VALUES
    ('CR-BKK-01',  'BKK', 'CR',  'Cisco',   'ASR-9010',  '7.5.2',  '10.10.0.1',  '2019-04-15'),
    ('CR-BKK-02',  'BKK', 'CR',  'Cisco',   'ASR-9010',  '7.5.2',  '10.10.0.2',  '2019-04-15'),
    ('PE-BKK-02',  'BKK', 'PE',  'Huawei',  'NE40E-X8',  'V800R011','10.10.1.2',  '2020-08-01'),
    ('APE-BKK-05', 'BKK', 'APE', 'Huawei',  'NE40E-X3',  'V800R011','10.10.2.5',  '2021-02-20'),
    ('PE-NBI-01',  'NBI', 'PE',  'Cisco',   'ASR-9006',  '7.5.2',  '10.20.1.1',  '2020-06-10'),
    ('PE-NBI-04',  'NBI', 'PE',  'Cisco',   'ASR-9006',  '7.4.1',  '10.20.1.4',  '2024-11-05'),
    ('APE-NBI-03', 'NBI', 'APE', 'Huawei',  'NE40E-X3',  'V800R011','10.20.2.3',  '2021-09-14'),
    ('LPE-NBI-11', 'NBI', 'LPE', 'Huawei',  'NE20E-S2F', 'V800R010','10.20.3.11', '2022-03-01'),
    ('LPE-NBI-12', 'NBI', 'LPE', 'Huawei',  'NE20E-S2F', 'V800R010','10.20.3.12', '2022-03-01'),
    ('LPE-NBI-13', 'NBI', 'LPE', 'Huawei',  'NE20E-S2F', 'V800R010','10.20.3.13', '2022-05-18');

-- ---------- Interfaces ----------
-- MTU matters: scenario S3 is an MTU mismatch between PE-NBI-04 (1500)
-- and its ISIS peer CR-BKK-02 (9000).

INSERT INTO interfaces (device_id, if_name, if_type, speed_mbps, mtu, description) VALUES
    ('CR-BKK-01',  'Hu0/0/0/0', 'peer',     100000, 9000, 'to CR-BKK-02'),
    ('CR-BKK-01',  'Hu0/0/0/1', 'downlink', 100000, 9000, 'to PE-NBI-01'),
    ('CR-BKK-01',  'Hu0/0/0/2', 'downlink', 100000, 9000, 'to PE-BKK-02'),
    ('CR-BKK-02',  'Hu0/0/0/0', 'peer',     100000, 9000, 'to CR-BKK-01'),
    ('CR-BKK-02',  'Te0/0/3',   'downlink',  10000, 9000, 'to PE-NBI-04 (ISIS peer)'),
    ('PE-BKK-02',  'Hu0/1/0/0', 'uplink',   100000, 9000, 'to CR-BKK-01'),
    ('PE-BKK-02',  'Te0/1/0/1', 'downlink',  10000, 9000, 'to APE-BKK-05'),
    ('PE-BKK-02',  'Te0/1/0/2', 'downlink',  10000, 9000, 'customer aggregation'),
    ('APE-BKK-05', 'Te0/1/1',   'uplink',    10000, 9000, 'to PE-BKK-02'),
    ('APE-BKK-05', 'Ge0/2/1',   'downlink',   1000, 1500, 'customer aggregation'),
    ('APE-BKK-05', 'Ge0/2/2',   'downlink',   1000, 1500, 'customer aggregation'),
    ('PE-NBI-01',  'Hu0/0/0/0', 'uplink',   100000, 9000, 'to CR-BKK-01'),
    ('PE-NBI-01',  'Te0/0/1',   'downlink',  10000, 9000, 'to APE-NBI-03'),
    ('PE-NBI-01',  'Te0/0/2',   'downlink',  10000, 9000, 'spare'),
    -- S3: this MTU is wrong. Its peer CR-BKK-02 Te0/0/3 uses 9000.
    ('PE-NBI-04',  'Te0/0/1',   'peer',      10000, 1500, 'to CR-BKK-02 (ISIS peer)'),
    ('PE-NBI-04',  'Te0/0/2',   'downlink',  10000, 9000, 'customer aggregation'),
    -- S1: this is the interface that flaps.
    ('APE-NBI-03', 'Te0/1/2',   'uplink',    10000, 9000, 'to PE-NBI-01'),
    ('APE-NBI-03', 'Ge0/2/1',   'downlink',   1000, 1500, 'to LPE-NBI-11'),
    ('APE-NBI-03', 'Ge0/2/2',   'downlink',   1000, 1500, 'to LPE-NBI-12'),
    ('APE-NBI-03', 'Ge0/2/3',   'downlink',   1000, 1500, 'to LPE-NBI-13'),
    ('LPE-NBI-11', 'Ge0/0/1',   'uplink',     1000, 1500, 'to APE-NBI-03'),
    ('LPE-NBI-11', 'Ge0/0/2',   'downlink',   1000, 1500, 'customer access'),
    ('LPE-NBI-11', 'Ge0/0/3',   'downlink',   1000, 1500, 'customer access'),
    ('LPE-NBI-12', 'Ge0/0/1',   'uplink',     1000, 1500, 'to APE-NBI-03'),
    ('LPE-NBI-12', 'Ge0/0/2',   'downlink',   1000, 1500, 'customer access'),
    ('LPE-NBI-13', 'Ge0/0/1',   'uplink',     1000, 1500, 'to APE-NBI-03'),
    ('LPE-NBI-13', 'Ge0/0/2',   'downlink',   1000, 1500, 'customer access'),
    ('LPE-NBI-13', 'Ge0/0/3',   'downlink',   1000, 1500, 'customer access');

-- ---------- Device configuration ----------
-- config_markdown is deliberately stored as Markdown: the ingestion lab
-- chunks and embeds these documents into OpenSearch.

INSERT INTO device_configs (device_id, isis_level, isis_metric, default_mtu, snmp_location, config_markdown) VALUES
    ('CR-BKK-01', 'level-2', 10, 9000, 'BKK-Core-Room-A', E'# CR-BKK-01\n\n## System\n- hostname CR-BKK-01\n- role: Core Router\n\n## ISIS\n- net 49.0001.0100.1000.0001.00\n- is-type level-2-only\n- metric 10\n\n## Interfaces\n- Hu0/0/0/0 mtu 9000 (to CR-BKK-02)\n- Hu0/0/0/1 mtu 9000 (to PE-NBI-01)\n- Hu0/0/0/2 mtu 9000 (to PE-BKK-02)\n'),
    ('CR-BKK-02', 'level-2', 10, 9000, 'BKK-Core-Room-B', E'# CR-BKK-02\n\n## System\n- hostname CR-BKK-02\n- role: Core Router\n\n## ISIS\n- net 49.0001.0100.1000.0002.00\n- is-type level-2-only\n- metric 10\n\n## Interfaces\n- Hu0/0/0/0 mtu 9000 (to CR-BKK-01)\n- Te0/0/3 mtu 9000 (to PE-NBI-04)\n'),
    ('PE-BKK-02', 'level-2', 20, 9000, 'BKK-Edge-Room-1', E'# PE-BKK-02\n\n## System\n- hostname PE-BKK-02\n- role: Provider Edge\n\n## ISIS\n- is-type level-2-only\n- metric 20\n\n## Interfaces\n- Hu0/1/0/0 mtu 9000 (uplink to CR-BKK-01)\n- Te0/1/0/1 mtu 9000 (to APE-BKK-05)\n- Te0/1/0/2 mtu 9000 (customer aggregation)\n'),
    ('APE-BKK-05','level-2', 30, 9000, 'BKK-Agg-Room-2',  E'# APE-BKK-05\n\n## System\n- hostname APE-BKK-05\n- role: Aggregation PE\n\n## Interfaces\n- Te0/1/1 mtu 9000 (uplink to PE-BKK-02)\n- Ge0/2/1 mtu 1500 (customer)\n- Ge0/2/2 mtu 1500 (customer)\n'),
    ('PE-NBI-01', 'level-2', 20, 9000, 'NBI-Edge-Room-1', E'# PE-NBI-01\n\n## System\n- hostname PE-NBI-01\n- role: Provider Edge\n\n## ISIS\n- is-type level-2-only\n- metric 20\n\n## Interfaces\n- Hu0/0/0/0 mtu 9000 (uplink to CR-BKK-01)\n- Te0/0/1 mtu 9000 (to APE-NBI-03)\n'),
    -- S3 root cause lives in this config: default_mtu 1500 on the ISIS peer link.
    ('PE-NBI-04', 'level-2', 20, 1500, 'NBI-Edge-Room-2', E'# PE-NBI-04\n\n## System\n- hostname PE-NBI-04\n- role: Provider Edge\n- installed: recent replacement\n\n## ISIS\n- is-type level-2-only\n- metric 20\n\n## Interfaces\n- Te0/0/1 mtu 1500 (to CR-BKK-02, ISIS peer)  <-- differs from peer\n- Te0/0/2 mtu 9000 (customer aggregation)\n'),
    ('APE-NBI-03','level-2', 30, 9000, 'NBI-Agg-Room-1',  E'# APE-NBI-03\n\n## System\n- hostname APE-NBI-03\n- role: Aggregation PE\n\n## Interfaces\n- Te0/1/2 mtu 9000 (uplink to PE-NBI-01)\n- Ge0/2/1 mtu 1500 (to LPE-NBI-11)\n- Ge0/2/2 mtu 1500 (to LPE-NBI-12)\n- Ge0/2/3 mtu 1500 (to LPE-NBI-13)\n'),
    ('LPE-NBI-11','level-1', 40, 1500, 'NBI-Access-A',    E'# LPE-NBI-11\n\n## System\n- hostname LPE-NBI-11\n- role: Local PE\n\n## Interfaces\n- Ge0/0/1 mtu 1500 (uplink to APE-NBI-03)\n- Ge0/0/2 mtu 1500 (customer access)\n- Ge0/0/3 mtu 1500 (customer access)\n'),
    ('LPE-NBI-12','level-1', 40, 1500, 'NBI-Access-B',    E'# LPE-NBI-12\n\n## System\n- hostname LPE-NBI-12\n- role: Local PE\n\n## Interfaces\n- Ge0/0/1 mtu 1500 (uplink to APE-NBI-03)\n- Ge0/0/2 mtu 1500 (customer access)\n'),
    ('LPE-NBI-13','level-1', 40, 1500, 'NBI-Access-C',    E'# LPE-NBI-13\n\n## System\n- hostname LPE-NBI-13\n- role: Local PE\n\n## Interfaces\n- Ge0/0/1 mtu 1500 (uplink to APE-NBI-03)\n- Ge0/0/2 mtu 1500 (customer access)\n- Ge0/0/3 mtu 1500 (customer access)\n');

-- ---------- Ticket categories ----------

INSERT INTO ticket_categories (code, name_th, description) VALUES
    ('link_down',    'ลิงก์ล่ม',            'Circuit or interface is completely down'),
    ('intermittent', 'หลุดเป็นช่วง',        'Service drops intermittently - the hardest class to diagnose'),
    ('slow',         'ช้าผิดปกติ',          'Throughput or latency degradation without full outage'),
    ('config',       'ตั้งค่าผิดพลาด',      'Configuration error or drift'),
    ('maintenance',  'งานบำรุงรักษาตามแผน', 'Planned work announced in advance - NOT an incident'),
    ('inquiry',      'สอบถามข้อมูล',        'Customer information request');
