-- ============================================================
-- Read-only role for the MCP server
--
-- This is the most important security control in the whole workshop:
-- even if a prompt injection convinces the model to issue a DELETE,
-- the database itself refuses. Guardrails in prompts are advisory;
-- guardrails in the permission layer are enforced.
--
-- Discussed in day3/module8-security-sdk.md and exercised in challenge5.
-- ============================================================

DO $$
DECLARE
    ro_user TEXT := coalesce(current_setting('mcp.readonly_user', true), 'mcp_reader');
    ro_pass TEXT := coalesce(current_setting('mcp.readonly_password', true), 'mcp_reader_password');
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = ro_user) THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', ro_user, ro_pass);
    END IF;

    EXECUTE format('GRANT CONNECT ON DATABASE %I TO %I', current_database(), ro_user);
    EXECUTE format('GRANT USAGE ON SCHEMA public TO %I', ro_user);
    EXECUTE format('GRANT SELECT ON ALL TABLES IN SCHEMA public TO %I', ro_user);
    EXECUTE format('GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO %I', ro_user);

    -- Any table created later (for example the embedding work in Lab 1)
    -- is also readable by the MCP server without another grant.
    EXECUTE format(
        'ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO %I', ro_user);

    -- Explicitly deny everything else. REVOKE is redundant for a fresh role
    -- but it documents intent and protects against a template with wider grants.
    EXECUTE format('REVOKE CREATE ON SCHEMA public FROM %I', ro_user);
END
$$;

-- Statement timeout so a runaway query generated by the model cannot
-- pin a connection forever.
ALTER ROLE mcp_reader SET statement_timeout = '15s';
ALTER ROLE mcp_reader SET idle_in_transaction_session_timeout = '30s';
